#!/usr/bin/env python

"""
Author: Saophalkun Ponlu (http://phalkunz.com)
Contact: phalkunz@gmail.com
Date: May 23, 2009
Modified: June 15, 2009

Additional modifications:
Author: Phil Christensen (http://bubblehouse.org)
Contact: phil@bubblehouse.org
Date: February 22, 2010

Author: Frederik Mogensen
Contact: mogensen@cs.au.dk
Date: December 20, 2011
"""

import os, sys, re, subprocess

tabsize = 4

colorizedSubcommands = (
	'status',
	'add',
	'remove',
	'diff',
	'log',
)

statusColors = {
	"\s*M"     : "31",     # red 
	"\?"    : "37",     # grey
	"\s*A"     : "32",     # green
	"X"     : "33",     # yellow
	#"C"     : "30;41",  # black on red
	"-"     : "31",     # red
	"\s*D"     : "31;1",   # bold red
	"\+"    : "32",     # green
	"\!"    : "36",     # green
}

def colorize(line): 
	for color in statusColors:
		if re.match(color, line):
			return ''.join(("\033[0;", statusColors[color], "m", line, "\033[m"))
	else:
		return line

def escape(s):
	s = s.replace('$', r'\$')
	s = s.replace('"', r'\"')
	s = s.replace('`', r'\`')
	return s

passthru = lambda x: x
quoted = lambda x: '"%s"' % escape(x)

if __name__ == "__main__":
	cmd = ' '.join(['svn']+[(passthru, quoted)[' ' in arg](arg) for arg in sys.argv[1:]])
	output = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE)
	cancelled = False
	for line in output.stdout:
		line = line.expandtabs(tabsize)
		if(sys.argv[1] in colorizedSubcommands):
			line = colorize(line)
			try:
				sys.stdout.write(line)
			except:
				sys.exit(1)
